import Navbar from '@/components/navbar';
import ThemeProvider from '@/contexts/theme-provider';
import { cn } from '@/lib/utils';
import '@/styles/globals.css';

import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang='en' className={cn(`min-h-screen ${inter.className}`)}>
            <body className={inter.className}>
                <ThemeProvider>
                    <Navbar />
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}
