import Footer from '@/components/footer';
import Navbar from '@/components/navbar';
import NextAuthSessionProvider from '@/contexts/next-auth-session-provider';
import ThemeProvider from '@/contexts/theme-provider';
import { cn } from '@/lib/utils';
import '@/styles/globals.css';

import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang='en' className={cn(`min-h-screen ${inter.className}`)}>
            <body className={inter.className}>
                <NextAuthSessionProvider>
                    <ThemeProvider>
                        {/* @ts-expect-error Server Component */}
                        <Navbar />
                        <div className='container p-4'>{children}</div>
                        <Footer />
                    </ThemeProvider>
                </NextAuthSessionProvider>
            </body>
        </html>
    );
}
