import SiteNav from "@/components/site-nav";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NextThemeProvider from "@/components/next-theme-provider";
import SiteFooter from "@/components/site-footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem={true}
        >
          <SiteNav />
          <main className="container mx-auto min-h-screen max-w-7xl py-8">
            {children}
          </main>
          <SiteFooter />
        </NextThemeProvider>
      </body>
    </html>
  );
}
